<?xml version="1.0" encoding="utf-8"?>
<Database Name="BurningPlate" EntityNamespace="BurningPlate.Data" ContextNamespace="BurningPlate.Data" Class="BurningPlateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Documents and Settings\claco\Desktop\ASP.NET\App_Data\BurningPlate.mdf&quot;;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BurningPlateConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Restaurants" Member="Restaurants">
    <Type Name="Restaurant">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>