dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'sqlite:%SF_ROOT_DIR%/db/development.db'
      username: root
      password: null
      encoding: utf8
      persistent: true
      pooling: true
